name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name TXTprocessor main.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: TXTprocessor.exe
        path: dist/TXTprocessor.exe

    - name: Upload to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/TXTprocessor.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

